### PR TITLE
added: climacons scss file, autotranslated from css

### PR DESCRIPTION
**Pull request by vlrmprjct**
A bit more flexibility with some variables.

### CODE REVIEW

**Comment by cliffordp** [comment]
I don't do scss but glancing at the code seems legit

**Comment by cliffordp** [comment]
Before merging, please first update the `package.json` version number to `1.1.0` (per https://docs.npmjs.com/files/package.json#version)

**Comment by vlrmprjct** [comment]
Drop PR

**Comment by cliffordp** [comment]
@vlrmprjct curious what happened... not using this anymore?

**Pull request closed without merging**
