### PR TITLE
added: package json for npm install via repository

### PR DESCRIPTION
**Pull request by vlrmprjct**
Just added a package.json for npm usage.
The magic is just  `npm install https://github.com/cliffordp/climacons-webfont`

### CODE REVIEW

**Comment by telekommander** [comment]
Did it.

**Comment by cliffordp** [comment]
The scss file wouldn't need to be referenced in this npm JSON file, correct? Assuming "correct", I've merged this PR. Please do a separate pull request if this file needs to be modified or if a new scss file(s) needs to be added.

Thanks for your contribution!

**Comment by telekommander** [comment]
> The scss file wouldn't need to be referenced in this npm JSON file, correct?

@cliffordp , thats correct. 

And I would prefer to add this repo to the NPM DB. But you do not necessarily need that.
Maybe it's a bit over the top for my taste. :)

**Comment by cliffordp** [comment]
OK, I won't add to NPM's site. If/when _you_ do, please add the bullet item to this repo's readme.

**Pull request merged**
